# Generated by Django 2.2.3 on 2019-07-16 13:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 13, 0, 11, 396808, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nickname')),
                ('description', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('1', '男性'), ('2', '女性')], max_length=2, verbose_name='性別')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('hobby', models.CharField(max_length=255, verbose_name='Hobby')),
                ('image', models.ImageField(upload_to='media/profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
