# Generated by Django 2.2.3 on 2019-07-18 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190718_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 14, 29, 26, 393359, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
