# Generated by Django 2.2.3 on 2019-07-18 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190718_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='yu-sekita', max_length=30, verbose_name='user name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 22, 7, 49, 72852, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
