# Generated by Django 2.2.3 on 2019-07-20 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190719_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 13, 14, 44, 977106, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
