version: '3.7'

services:
  api:
    build:
        context: ./
        dockerfile: ./.docker/Dockerfile
    command: python /server/manage.py runserver 0.0.0.0:8000
    volumes:
    - ./:/server
    ports:
    - 8000:8000