version: '3.7'

services:
    web:
        env_file: .env
        build:
            context: ./
            dockerfile: ./.docker/Dockerfile
        command: >
            bash -c 'python manage.py migrate &&
            python manage.py collectstatic --no-input &&
            gunicorn config.wsgi --bind 0.0.0.0:8000'
        volumes:
        - ./:/server
        - ./staticfiles:/server/staticfiles
        expose:
        - 8000

    nginx:
        build: ./nginx
        volumes:
        - /www/static
        ports:
          - 1337:80
        depends_on:
          - web

volumes:
    static_volume: