version: '3.7'

services:
  api:
    env_file: .env
    build:
        context: ./
        dockerfile: ./.docker/Dockerfile
    command: >
        bash -c 'python manage.py migrate &&
        python /server/manage.py runserver 0.0.0.0:8000'
    volumes:
    - ./:/server
    ports:
    - 8000:8000