# Generated by Django 2.2.1 on 2019-05-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190526_0435'),
        ('blog', '0003_auto_20190526_0010'),
    ]

    operations = [
    ]
