# Generated by Django 2.2.1 on 2019-05-26 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20190526_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 5, 37, 37, 436225, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
