# Generated by Django 2.2.1 on 2019-05-26 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190526_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 5, 58, 24, 80413, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
