# Generated by Django 2.2.1 on 2019-06-02 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    # dependencies = [
    #     ('blog', '0009_auto_20190601_0724'),
    # ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 2, 6, 57, 899878, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
