version: 2
jobs:
    lint:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: |
                pipenv install flake8
                cd blogs
                pipenv run flake8 tests
                pipenv run flake8 escape.py
                pipenv run flake8 forms.py
                pipenv run flake8 models.py
                pipenv run flake8 urls.py
                pipenv run flake8 views.py
                cd ../users
                pipenv run flake8 tests
                pipenv run flake8 forms.py
                pipenv run flake8 models.py
                pipenv run flake8 urls.py
                pipenv run flake8 views.py

    test:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: echo $ENV_FILE | base64 -di > .env
            - run: |
                pipenv install django==2.2.9
                pipenv run python manage.py migrate
                pipenv run python manage.py test

    deploy:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run:
                name: heroku deploy
                command: |
                    git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


workflows:
    version: 2
    myworkflow:
        jobs:
            - lint
            - test:
                requires:
                    - lint
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        only: master
