version: 2
jobs:
    lint:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: |
                pipenv install flake8
                cd Tech_Blog/blogs
                pipenv run flake8 forms.py
                pipenv run flake8 models.py
                pipenv run flake8 urls.py
                pipenv run flake8 views.py

    test:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: |
                pipenv install django==2.2.1
                cd Tech_Blog
                pipenv run python manage.py migrate
                pipenv run python manage.py test

workflows:
    version: 2
    myworkflow:
        jobs:
            - lint
            - test:
                requires:
                    - lint
