version: 2
jobs:
    lint:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: |
                pipenv install flake8
                cd Tech_Blog
                flake8 blog

    test:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: |
                pipenv install django==2.2.1
                cd Tech_Blog
                pipenv run python manage.py migrate
                pipenv run python manage.py test

workflows:
    version: 2
    myworkflow:
        jobs:
            - test:
                requires:
                    - lint
