version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: |
                pipenv install django==2.2.1
                pipenv shell
                cd Tech_Blog
                python manage.py migrate
                python manage.py test
