version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: |
                pipenv install django==2.2.1
                cd Tech_Blog
                pipenv run python manage.py makemigrations
                pipenv run python manage.py migrate
                pipenv run python manage.py test
