# Generated by Django 2.2.2 on 2019-06-22 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 6, 22, 9, 5, 31, 416261, tzinfo=utc), verbose_name='作成日')),
            ],
        ),
    ]
