# Generated by Django 2.2.3 on 2019-07-16 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 13, 0, 11, 400602, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
