# Generated by Django 2.2.3 on 2019-07-17 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190716_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 14, 17, 10, 305273, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
