# Generated by Django 2.2.3 on 2019-07-20 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190719_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 13, 14, 44, 979937, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
