# Generated by Django 2.2.3 on 2019-07-24 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190720_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公開'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 11, 26, 24, 420628, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
