# Generated by Django 2.2.3 on 2019-08-04 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190724_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 2, 46, 32, 257748, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
