# Generated by Django 2.2.3 on 2019-08-13 00:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20190804_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 0, 36, 30, 443077, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
