# Generated by Django 2.2.4 on 2019-08-16 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20190813_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 6, 24, 8, 950523, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
