# Generated by Django 2.2.9 on 2020-04-12 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20190901_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_for_seo',
            field=models.CharField(max_length=255, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 7, 1, 44, 935455, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
