# Generated by Django 2.2.1 on 2019-06-12 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 6, 30, 13, 338299, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
