# Generated by Django 2.2.1 on 2019-05-26 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190526_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 0, 10, 43, 878208, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
