# Generated by Django 2.2.1 on 2019-06-01 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190601_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 7, 24, 11, 727999, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
