# Generated by Django 2.2.1 on 2019-06-10 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190602_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 10, 13, 37, 26, 52683, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='本文'),
        ),
    ]
